name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.10
          - 3.11
          - 3.12
          - 3.13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        if: contains( matrix.os, 'ubuntu')
        run: |
          python -m pip install --upgrade pip
          pip install hatch pdoc

      - name: Compile
        run: hatch build

      - name: Run tests
        run: |
          ls -la
          ls -la ./dist
          python -m pip install dist/*.whl
          cd tests
          python pyrandyos_test.py

      - name: Build documentation
        run: pdoc ./pyrandyos --docformat google --output-dir ./docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
